apiVersion: apps/v1
kind: Deployment
metadata:
  name: tennetbalancedeltaaditya
  namespace: process
spec:
  selector:
    matchLabels:
      app: tennetbalancedeltaaditya
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: tennetbalancedeltaaditya
    spec:
      hostname: tennetbalancedeltaaditya
      containers:
      - env:
        - name: DATA_SOURCE
          value: "tennet_balance_delta_aditya"
        - name: PYTHONHASHEED
          value: "1"
        - name: KAFKAHOST
          value: "kafka-svc.kafkazk.svc.cluster.local:9092"
        - name: TOPIC
          value: tennet_balance_delta_aditya
        - name: SQL_DRIVER
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SQL_DRIVER
        - name: SQL_HOST
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SQL_HOST
        - name: SQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SQL_USERNAME
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-pass
              key: password
        - name: SQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: SQL_DATABASE
        - name: KAFKA_FT_BLOB_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: blob-storage-credentials
              key: account_name
        - name: KAFKA_FT_BLOB_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: blob-storage-credentials
              key: account_key
        image: datahub.azurecr.io/tennetbalancedeltaaditya
        imagePullPolicy: Always
        name: tennetbalancedeltaaditya
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "400Mi"
      volumes:
      - name: secret-volume
        secret:
          secretName: sbp-ssh-key
      imagePullSecrets:
      - name: azure-acr-secret

